name: CI

on:
  schedule:
    - cron: '0 1 * * 1-5'
    - cron: '30 3 * * 1-5'
    - cron: '0 6 * * 1-5'
    - cron: '0 9 * * 1-5'
    - cron: '0 12 * * 1-5'
    - cron: '0 4 * * 0,6'

  workflow_dispatch:
    inputs:
      count:
        description: 'count'
        required: false
        default: '1'
        type: choice
        options: ['1', '2', '3', '4', '5']

concurrency:
  group: ci
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: setup
        run: |
          git config user.name  "${{ vars.GIT_AUTHOR_NAME }}"
          git config user.email "${{ vars.GIT_AUTHOR_EMAIL }}"

      - name: run
        env:
          COMMIT_COUNT: ${{ github.event.inputs.count || '1' }}
        run: python scripts/generate.py

      - name: push
        run: git push origin HEAD
